/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain.tables.records;


import cn.vertxup.ix.domain.tables.SRelPermAction;
import cn.vertxup.ix.domain.tables.interfaces.ISRelPermAction;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SRelPermActionRecord extends UpdatableRecordImpl<SRelPermActionRecord> implements Record2<String, String>, ISRelPermAction {

    private static final long serialVersionUID = 480390735;

    /**
     * Setter for <code>DB_ORIGIN_X.S_REL_PERM_ACTION.PERM_ID</code>. 「permId」- 关联权限ID
     */
    @Override
    public SRelPermActionRecord setPermId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_REL_PERM_ACTION.PERM_ID</code>. 「permId」- 关联权限ID
     */
    @Override
    public String getPermId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_REL_PERM_ACTION.ACTION_ID</code>. 「actionId」- 操作ID
     */
    @Override
    public SRelPermActionRecord setActionId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_REL_PERM_ACTION.ACTION_ID</code>. 「actionId」- 操作ID
     */
    @Override
    public String getActionId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SRelPermAction.S_REL_PERM_ACTION.PERM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SRelPermAction.S_REL_PERM_ACTION.ACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getPermId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getActionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPermId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getActionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SRelPermActionRecord value1(String value) {
        setPermId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SRelPermActionRecord value2(String value) {
        setActionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SRelPermActionRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ISRelPermAction from) {
        setPermId(from.getPermId());
        setActionId(from.getActionId());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ISRelPermAction> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SRelPermActionRecord
     */
    public SRelPermActionRecord() {
        super(SRelPermAction.S_REL_PERM_ACTION);
    }

    /**
     * Create a detached, initialised SRelPermActionRecord
     */
    public SRelPermActionRecord(String permId, String actionId) {
        super(SRelPermAction.S_REL_PERM_ACTION);

        set(0, permId);
        set(1, actionId);
    }
}
