/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain.tables.records;


import cn.vertxup.ix.domain.tables.SRelResourceMatrix;
import cn.vertxup.ix.domain.tables.interfaces.ISRelResourceMatrix;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SRelResourceMatrixRecord extends UpdatableRecordImpl<SRelResourceMatrixRecord> implements Record6<String, String, String, LocalDateTime, String, String>, ISRelResourceMatrix {

    private static final long serialVersionUID = -447596830;

    /**
     * Setter for <code>DB_ORIGIN_X.S_REL_RESOURCE_MATRIX.KEY</code>. 「key」- 限定记录ID
     */
    @Override
    public SRelResourceMatrixRecord setKey(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_REL_RESOURCE_MATRIX.KEY</code>. 「key」- 限定记录ID
     */
    @Override
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_REL_RESOURCE_MATRIX.ROLE_ID</code>. 「roleId」- 限定角色ID
     */
    @Override
    public SRelResourceMatrixRecord setRoleId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_REL_RESOURCE_MATRIX.ROLE_ID</code>. 「roleId」- 限定角色ID
     */
    @Override
    public String getRoleId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_REL_RESOURCE_MATRIX.USER_ID</code>. 「userId」- 限定用户ID
     */
    @Override
    public SRelResourceMatrixRecord setUserId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_REL_RESOURCE_MATRIX.USER_ID</code>. 「userId」- 限定用户ID
     */
    @Override
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_REL_RESOURCE_MATRIX.EXPIRED</code>. 「expired」- 资源过期时间（动态授权）
     */
    @Override
    public SRelResourceMatrixRecord setExpired(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_REL_RESOURCE_MATRIX.EXPIRED</code>. 「expired」- 资源过期时间（动态授权）
     */
    @Override
    public LocalDateTime getExpired() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_REL_RESOURCE_MATRIX.RESOURCE_ID</code>. 「resourceId」- 关联资源ID
     */
    @Override
    public SRelResourceMatrixRecord setResourceId(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_REL_RESOURCE_MATRIX.RESOURCE_ID</code>. 「resourceId」- 关联资源ID
     */
    @Override
    public String getResourceId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_REL_RESOURCE_MATRIX.APP_KEY</code>. 「appKey」- 所属APP的APPKEY
     */
    @Override
    public SRelResourceMatrixRecord setAppKey(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_REL_RESOURCE_MATRIX.APP_KEY</code>. 「appKey」- 所属APP的APPKEY
     */
    @Override
    public String getAppKey() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, LocalDateTime, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, LocalDateTime, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SRelResourceMatrix.S_REL_RESOURCE_MATRIX.KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SRelResourceMatrix.S_REL_RESOURCE_MATRIX.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SRelResourceMatrix.S_REL_RESOURCE_MATRIX.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return SRelResourceMatrix.S_REL_RESOURCE_MATRIX.EXPIRED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SRelResourceMatrix.S_REL_RESOURCE_MATRIX.RESOURCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SRelResourceMatrix.S_REL_RESOURCE_MATRIX.APP_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getExpired();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getResourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getAppKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getExpired();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getResourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAppKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SRelResourceMatrixRecord value1(String value) {
        setKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SRelResourceMatrixRecord value2(String value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SRelResourceMatrixRecord value3(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SRelResourceMatrixRecord value4(LocalDateTime value) {
        setExpired(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SRelResourceMatrixRecord value5(String value) {
        setResourceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SRelResourceMatrixRecord value6(String value) {
        setAppKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SRelResourceMatrixRecord values(String value1, String value2, String value3, LocalDateTime value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ISRelResourceMatrix from) {
        setKey(from.getKey());
        setRoleId(from.getRoleId());
        setUserId(from.getUserId());
        setExpired(from.getExpired());
        setResourceId(from.getResourceId());
        setAppKey(from.getAppKey());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ISRelResourceMatrix> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SRelResourceMatrixRecord
     */
    public SRelResourceMatrixRecord() {
        super(SRelResourceMatrix.S_REL_RESOURCE_MATRIX);
    }

    /**
     * Create a detached, initialised SRelResourceMatrixRecord
     */
    public SRelResourceMatrixRecord(String key, String roleId, String userId, LocalDateTime expired, String resourceId, String appKey) {
        super(SRelResourceMatrix.S_REL_RESOURCE_MATRIX);

        set(0, key);
        set(1, roleId);
        set(2, userId);
        set(3, expired);
        set(4, resourceId);
        set(5, appKey);
    }
}
