/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain.tables.records;


import cn.vertxup.ix.domain.tables.SUser;
import cn.vertxup.ix.domain.tables.interfaces.ISUser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SUserRecord extends UpdatableRecordImpl<SUserRecord> implements Record15<String, String, String, String, String, String, String, String, String, String, String, String, String, Boolean, String>, ISUser {

    private static final long serialVersionUID = 160816586;

    /**
     * Setter for <code>DB_ORIGIN_X.S_USER.KEY</code>. 「key」- 用户ID
     */
    @Override
    public SUserRecord setKey(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_USER.KEY</code>. 「key」- 用户ID
     */
    @Override
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_USER.USERNAME</code>. 「username」- 用户登录账号
     */
    @Override
    public SUserRecord setUsername(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_USER.USERNAME</code>. 「username」- 用户登录账号
     */
    @Override
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_USER.REALNAME</code>. 「realname」- 用户真实姓名
     */
    @Override
    public SUserRecord setRealname(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_USER.REALNAME</code>. 「realname」- 用户真实姓名
     */
    @Override
    public String getRealname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_USER.ALIAS</code>. 「alias」- 用户昵称
     */
    @Override
    public SUserRecord setAlias(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_USER.ALIAS</code>. 「alias」- 用户昵称
     */
    @Override
    public String getAlias() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_USER.MOBILE</code>. 「mobile」- 用户登录手机
     */
    @Override
    public SUserRecord setMobile(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_USER.MOBILE</code>. 「mobile」- 用户登录手机
     */
    @Override
    public String getMobile() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_USER.EMAIL</code>. 「email」- 用户登录EMAIL地址
     */
    @Override
    public SUserRecord setEmail(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_USER.EMAIL</code>. 「email」- 用户登录EMAIL地址
     */
    @Override
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_USER.PASSWORD</code>. 「password」- 用户登录密码
     */
    @Override
    public SUserRecord setPassword(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_USER.PASSWORD</code>. 「password」- 用户登录密码
     */
    @Override
    public String getPassword() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_USER.CATEGORY</code>. 「category」- 用户分类
     */
    @Override
    public SUserRecord setCategory(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_USER.CATEGORY</code>. 「category」- 用户分类
     */
    @Override
    public String getCategory() {
        return (String) get(7);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_USER.APP_KEY</code>. 「appKey」- 所属APP的APPKEY
     */
    @Override
    public SUserRecord setAppKey(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_USER.APP_KEY</code>. 「appKey」- 所属APP的APPKEY
     */
    @Override
    public String getAppKey() {
        return (String) get(8);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_USER.SECRET</code>. 「secret」- 平台为用户分发的密钥
     */
    @Override
    public SUserRecord setSecret(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_USER.SECRET</code>. 「secret」- 平台为用户分发的密钥
     */
    @Override
    public String getSecret() {
        return (String) get(9);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_USER.MODEL_ID</code>. 「modelId」- 用户所关联的模型identifier，用于描述
     */
    @Override
    public SUserRecord setModelId(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_USER.MODEL_ID</code>. 「modelId」- 用户所关联的模型identifier，用于描述
     */
    @Override
    public String getModelId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_USER.MODEL_KEY</code>. 「modelKey」- 用户所关联的模型记录ID，用于描述哪一个Model中的记录
     */
    @Override
    public SUserRecord setModelKey(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_USER.MODEL_KEY</code>. 「modelKey」- 用户所关联的模型记录ID，用于描述哪一个Model中的记录
     */
    @Override
    public String getModelKey() {
        return (String) get(11);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_USER.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public SUserRecord setLanguage(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_USER.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public String getLanguage() {
        return (String) get(12);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_USER.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public SUserRecord setActive(Boolean value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_USER.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public Boolean getActive() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.S_USER.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public SUserRecord setMetadata(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.S_USER.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public String getMetadata() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, String, String, String, String, String, String, String, String, String, String, String, String, Boolean, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<String, String, String, String, String, String, String, String, String, String, String, String, String, Boolean, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SUser.S_USER.KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SUser.S_USER.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SUser.S_USER.REALNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SUser.S_USER.ALIAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SUser.S_USER.MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SUser.S_USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SUser.S_USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return SUser.S_USER.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return SUser.S_USER.APP_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return SUser.S_USER.SECRET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return SUser.S_USER.MODEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return SUser.S_USER.MODEL_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return SUser.S_USER.LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return SUser.S_USER.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return SUser.S_USER.METADATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRealname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAlias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getAppKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getSecret();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getModelKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component14() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getMetadata();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRealname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAlias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getAppKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getSecret();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getModelKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getMetadata();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserRecord value1(String value) {
        setKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserRecord value2(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserRecord value3(String value) {
        setRealname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserRecord value4(String value) {
        setAlias(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserRecord value5(String value) {
        setMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserRecord value6(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserRecord value7(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserRecord value8(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserRecord value9(String value) {
        setAppKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserRecord value10(String value) {
        setSecret(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserRecord value11(String value) {
        setModelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserRecord value12(String value) {
        setModelKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserRecord value13(String value) {
        setLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserRecord value14(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserRecord value15(String value) {
        setMetadata(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SUserRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, Boolean value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ISUser from) {
        setKey(from.getKey());
        setUsername(from.getUsername());
        setRealname(from.getRealname());
        setAlias(from.getAlias());
        setMobile(from.getMobile());
        setEmail(from.getEmail());
        setPassword(from.getPassword());
        setCategory(from.getCategory());
        setAppKey(from.getAppKey());
        setSecret(from.getSecret());
        setModelId(from.getModelId());
        setModelKey(from.getModelKey());
        setLanguage(from.getLanguage());
        setActive(from.getActive());
        setMetadata(from.getMetadata());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ISUser> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SUserRecord
     */
    public SUserRecord() {
        super(SUser.S_USER);
    }

    /**
     * Create a detached, initialised SUserRecord
     */
    public SUserRecord(String key, String username, String realname, String alias, String mobile, String email, String password, String category, String appKey, String secret, String modelId, String modelKey, String language, Boolean active, String metadata) {
        super(SUser.S_USER);

        set(0, key);
        set(1, username);
        set(2, realname);
        set(3, alias);
        set(4, mobile);
        set(5, email);
        set(6, password);
        set(7, category);
        set(8, appKey);
        set(9, secret);
        set(10, modelId);
        set(11, modelKey);
        set(12, language);
        set(13, active);
        set(14, metadata);
    }
}
