/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain.tables;


import cn.vertxup.ix.domain.DbOriginX;
import cn.vertxup.ix.domain.Indexes;
import cn.vertxup.ix.domain.Keys;
import cn.vertxup.ix.domain.tables.records.SActionRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SAction extends TableImpl<SActionRecord> {

    private static final long serialVersionUID = -1260671573;

    /**
     * The reference instance of <code>DB_ORIGIN_X.S_ACTION</code>
     */
    public static final SAction S_ACTION = new SAction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SActionRecord> getRecordType() {
        return SActionRecord.class;
    }

    /**
     * The column <code>DB_ORIGIN_X.S_ACTION.KEY</code>. 「key」- 操作ID
     */
    public final TableField<SActionRecord, String> KEY = createField("KEY", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "「key」- 操作ID");

    /**
     * The column <code>DB_ORIGIN_X.S_ACTION.NAME</code>. 「name」- 操作名称
     */
    public final TableField<SActionRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(255), this, "「name」- 操作名称");

    /**
     * The column <code>DB_ORIGIN_X.S_ACTION.CODE</code>. 「code」- 操作码
     */
    public final TableField<SActionRecord, String> CODE = createField("CODE", org.jooq.impl.SQLDataType.VARCHAR(255), this, "「code」- 操作码");

    /**
     * The column <code>DB_ORIGIN_X.S_ACTION.LEVEL</code>. 「level」- 操作级别
     */
    public final TableField<SActionRecord, Integer> LEVEL = createField("LEVEL", org.jooq.impl.SQLDataType.INTEGER, this, "「level」- 操作级别");

    /**
     * The column <code>DB_ORIGIN_X.S_ACTION.PRIORITY</code>. 「priority」- 操作优先级：用户优先、角色优先、统一（定义资源的访问表）
     */
    public final TableField<SActionRecord, String> PRIORITY = createField("PRIORITY", org.jooq.impl.SQLDataType.VARCHAR(32), this, "「priority」- 操作优先级：用户优先、角色优先、统一（定义资源的访问表）");

    /**
     * The column <code>DB_ORIGIN_X.S_ACTION.CATEGORY</code>. 「category」- 操作类型
     */
    public final TableField<SActionRecord, String> CATEGORY = createField("CATEGORY", org.jooq.impl.SQLDataType.VARCHAR(36), this, "「category」- 操作类型");

    /**
     * The column <code>DB_ORIGIN_X.S_ACTION.APP_KEY</code>. 「appKey」- 所属APP的APPKEY
     */
    public final TableField<SActionRecord, String> APP_KEY = createField("APP_KEY", org.jooq.impl.SQLDataType.VARCHAR(128), this, "「appKey」- 所属APP的APPKEY");

    /**
     * The column <code>DB_ORIGIN_X.S_ACTION.LANGUAGE</code>. 「language」- 使用的语言
     */
    public final TableField<SActionRecord, String> LANGUAGE = createField("LANGUAGE", org.jooq.impl.SQLDataType.VARCHAR(10), this, "「language」- 使用的语言");

    /**
     * The column <code>DB_ORIGIN_X.S_ACTION.ACTIVE</code>. 「active」- 是否启用
     */
    public final TableField<SActionRecord, Boolean> ACTIVE = createField("ACTIVE", org.jooq.impl.SQLDataType.BIT, this, "「active」- 是否启用");

    /**
     * The column <code>DB_ORIGIN_X.S_ACTION.METADATA</code>. 「metadata」- 附加配置数据
     */
    public final TableField<SActionRecord, String> METADATA = createField("METADATA", org.jooq.impl.SQLDataType.CLOB, this, "「metadata」- 附加配置数据");

    /**
     * The column <code>DB_ORIGIN_X.S_ACTION.RESOURCE_ID</code>. 「resourceId」- 操作关联资源ID
     */
    public final TableField<SActionRecord, String> RESOURCE_ID = createField("RESOURCE_ID", org.jooq.impl.SQLDataType.VARCHAR(36), this, "「resourceId」- 操作关联资源ID");

    /**
     * Create a <code>DB_ORIGIN_X.S_ACTION</code> table reference
     */
    public SAction() {
        this(DSL.name("S_ACTION"), null);
    }

    /**
     * Create an aliased <code>DB_ORIGIN_X.S_ACTION</code> table reference
     */
    public SAction(String alias) {
        this(DSL.name(alias), S_ACTION);
    }

    /**
     * Create an aliased <code>DB_ORIGIN_X.S_ACTION</code> table reference
     */
    public SAction(Name alias) {
        this(alias, S_ACTION);
    }

    private SAction(Name alias, Table<SActionRecord> aliased) {
        this(alias, aliased, null);
    }

    private SAction(Name alias, Table<SActionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbOriginX.DB_ORIGIN_X;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.S_ACTION_CODE, Indexes.S_ACTION_PRIMARY, Indexes.S_ACTION_RESOURCE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SActionRecord> getPrimaryKey() {
        return Keys.KEY_S_ACTION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SActionRecord>> getKeys() {
        return Arrays.<UniqueKey<SActionRecord>>asList(Keys.KEY_S_ACTION_PRIMARY, Keys.KEY_S_ACTION_CODE, Keys.KEY_S_ACTION_RESOURCE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SAction as(String alias) {
        return new SAction(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SAction as(Name alias) {
        return new SAction(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SAction rename(String name) {
        return new SAction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SAction rename(Name name) {
        return new SAction(name, null);
    }
}
