/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain.tables;


import cn.vertxup.ix.domain.DbOriginX;
import cn.vertxup.ix.domain.Indexes;
import cn.vertxup.ix.domain.Keys;
import cn.vertxup.ix.domain.tables.records.SPermissionRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SPermission extends TableImpl<SPermissionRecord> {

    private static final long serialVersionUID = 1080958966;

    /**
     * The reference instance of <code>DB_ORIGIN_X.S_PERMISSION</code>
     */
    public static final SPermission S_PERMISSION = new SPermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SPermissionRecord> getRecordType() {
        return SPermissionRecord.class;
    }

    /**
     * The column <code>DB_ORIGIN_X.S_PERMISSION.KEY</code>. 「key」- 权限ID
     */
    public final TableField<SPermissionRecord, String> KEY = createField("KEY", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "「key」- 权限ID");

    /**
     * The column <code>DB_ORIGIN_X.S_PERMISSION.NAME</code>. 「name」- 权限名称
     */
    public final TableField<SPermissionRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(255), this, "「name」- 权限名称");

    /**
     * The column <code>DB_ORIGIN_X.S_PERMISSION.CODE</code>. 「code」- 权限系统码
     */
    public final TableField<SPermissionRecord, String> CODE = createField("CODE", org.jooq.impl.SQLDataType.VARCHAR(255), this, "「code」- 权限系统码");

    /**
     * The column <code>DB_ORIGIN_X.S_PERMISSION.PRIORITY</code>. 「priority」- 权限优先级：角色优先、组优先、用户优先
     */
    public final TableField<SPermissionRecord, String> PRIORITY = createField("PRIORITY", org.jooq.impl.SQLDataType.VARCHAR(32), this, "「priority」- 权限优先级：角色优先、组优先、用户优先");

    /**
     * The column <code>DB_ORIGIN_X.S_PERMISSION.MODE</code>. 「mode」- 继承、限制、时域、指定
     */
    public final TableField<SPermissionRecord, String> MODE = createField("MODE", org.jooq.impl.SQLDataType.VARCHAR(32), this, "「mode」- 继承、限制、时域、指定");

    /**
     * The column <code>DB_ORIGIN_X.S_PERMISSION.APP_KEY</code>. 「appKey」- 所属APP的APPKEY
     */
    public final TableField<SPermissionRecord, String> APP_KEY = createField("APP_KEY", org.jooq.impl.SQLDataType.VARCHAR(128), this, "「appKey」- 所属APP的APPKEY");

    /**
     * The column <code>DB_ORIGIN_X.S_PERMISSION.LANGUAGE</code>. 「language」- 使用的语言
     */
    public final TableField<SPermissionRecord, String> LANGUAGE = createField("LANGUAGE", org.jooq.impl.SQLDataType.VARCHAR(10), this, "「language」- 使用的语言");

    /**
     * The column <code>DB_ORIGIN_X.S_PERMISSION.ACTIVE</code>. 「active」- 是否启用
     */
    public final TableField<SPermissionRecord, Boolean> ACTIVE = createField("ACTIVE", org.jooq.impl.SQLDataType.BIT, this, "「active」- 是否启用");

    /**
     * The column <code>DB_ORIGIN_X.S_PERMISSION.METADATA</code>. 「metadata」- 附加配置数据
     */
    public final TableField<SPermissionRecord, String> METADATA = createField("METADATA", org.jooq.impl.SQLDataType.CLOB, this, "「metadata」- 附加配置数据");

    /**
     * Create a <code>DB_ORIGIN_X.S_PERMISSION</code> table reference
     */
    public SPermission() {
        this(DSL.name("S_PERMISSION"), null);
    }

    /**
     * Create an aliased <code>DB_ORIGIN_X.S_PERMISSION</code> table reference
     */
    public SPermission(String alias) {
        this(DSL.name(alias), S_PERMISSION);
    }

    /**
     * Create an aliased <code>DB_ORIGIN_X.S_PERMISSION</code> table reference
     */
    public SPermission(Name alias) {
        this(alias, S_PERMISSION);
    }

    private SPermission(Name alias, Table<SPermissionRecord> aliased) {
        this(alias, aliased, null);
    }

    private SPermission(Name alias, Table<SPermissionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbOriginX.DB_ORIGIN_X;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.S_PERMISSION_CODE, Indexes.S_PERMISSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SPermissionRecord> getPrimaryKey() {
        return Keys.KEY_S_PERMISSION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SPermissionRecord>> getKeys() {
        return Arrays.<UniqueKey<SPermissionRecord>>asList(Keys.KEY_S_PERMISSION_PRIMARY, Keys.KEY_S_PERMISSION_CODE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SPermission as(String alias) {
        return new SPermission(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SPermission as(Name alias) {
        return new SPermission(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SPermission rename(String name) {
        return new SPermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SPermission rename(Name name) {
        return new SPermission(name, null);
    }
}
