/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain.tables;


import cn.vertxup.ix.domain.DbOriginX;
import cn.vertxup.ix.domain.Indexes;
import cn.vertxup.ix.domain.Keys;
import cn.vertxup.ix.domain.tables.records.SRelGroupRoleRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SRelGroupRole extends TableImpl<SRelGroupRoleRecord> {

    private static final long serialVersionUID = 544851791;

    /**
     * The reference instance of <code>DB_ORIGIN_X.S_REL_GROUP_ROLE</code>
     */
    public static final SRelGroupRole S_REL_GROUP_ROLE = new SRelGroupRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SRelGroupRoleRecord> getRecordType() {
        return SRelGroupRoleRecord.class;
    }

    /**
     * The column <code>DB_ORIGIN_X.S_REL_GROUP_ROLE.GROUP_ID</code>. 「groupId」- 关联组ID
     */
    public final TableField<SRelGroupRoleRecord, String> GROUP_ID = createField("GROUP_ID", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "「groupId」- 关联组ID");

    /**
     * The column <code>DB_ORIGIN_X.S_REL_GROUP_ROLE.ROLE_ID</code>. 「roleId」- 关联角色ID
     */
    public final TableField<SRelGroupRoleRecord, String> ROLE_ID = createField("ROLE_ID", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "「roleId」- 关联角色ID");

    /**
     * Create a <code>DB_ORIGIN_X.S_REL_GROUP_ROLE</code> table reference
     */
    public SRelGroupRole() {
        this(DSL.name("S_REL_GROUP_ROLE"), null);
    }

    /**
     * Create an aliased <code>DB_ORIGIN_X.S_REL_GROUP_ROLE</code> table reference
     */
    public SRelGroupRole(String alias) {
        this(DSL.name(alias), S_REL_GROUP_ROLE);
    }

    /**
     * Create an aliased <code>DB_ORIGIN_X.S_REL_GROUP_ROLE</code> table reference
     */
    public SRelGroupRole(Name alias) {
        this(alias, S_REL_GROUP_ROLE);
    }

    private SRelGroupRole(Name alias, Table<SRelGroupRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private SRelGroupRole(Name alias, Table<SRelGroupRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbOriginX.DB_ORIGIN_X;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.S_REL_GROUP_ROLE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SRelGroupRoleRecord> getPrimaryKey() {
        return Keys.KEY_S_REL_GROUP_ROLE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SRelGroupRoleRecord>> getKeys() {
        return Arrays.<UniqueKey<SRelGroupRoleRecord>>asList(Keys.KEY_S_REL_GROUP_ROLE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SRelGroupRole as(String alias) {
        return new SRelGroupRole(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SRelGroupRole as(Name alias) {
        return new SRelGroupRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SRelGroupRole rename(String name) {
        return new SRelGroupRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SRelGroupRole rename(Name name) {
        return new SRelGroupRole(name, null);
    }
}
