/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain.tables;


import cn.vertxup.ix.domain.DbOriginX;
import cn.vertxup.ix.domain.Indexes;
import cn.vertxup.ix.domain.Keys;
import cn.vertxup.ix.domain.tables.records.SRelUserGroupRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SRelUserGroup extends TableImpl<SRelUserGroupRecord> {

    private static final long serialVersionUID = 93251411;

    /**
     * The reference instance of <code>DB_ORIGIN_X.S_REL_USER_GROUP</code>
     */
    public static final SRelUserGroup S_REL_USER_GROUP = new SRelUserGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SRelUserGroupRecord> getRecordType() {
        return SRelUserGroupRecord.class;
    }

    /**
     * The column <code>DB_ORIGIN_X.S_REL_USER_GROUP.GROUP_ID</code>. 「groupId」- 关联组ID
     */
    public final TableField<SRelUserGroupRecord, String> GROUP_ID = createField("GROUP_ID", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "「groupId」- 关联组ID");

    /**
     * The column <code>DB_ORIGIN_X.S_REL_USER_GROUP.ROLE_ID</code>. 「roleId」- 关联角色ID
     */
    public final TableField<SRelUserGroupRecord, String> ROLE_ID = createField("ROLE_ID", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "「roleId」- 关联角色ID");

    /**
     * Create a <code>DB_ORIGIN_X.S_REL_USER_GROUP</code> table reference
     */
    public SRelUserGroup() {
        this(DSL.name("S_REL_USER_GROUP"), null);
    }

    /**
     * Create an aliased <code>DB_ORIGIN_X.S_REL_USER_GROUP</code> table reference
     */
    public SRelUserGroup(String alias) {
        this(DSL.name(alias), S_REL_USER_GROUP);
    }

    /**
     * Create an aliased <code>DB_ORIGIN_X.S_REL_USER_GROUP</code> table reference
     */
    public SRelUserGroup(Name alias) {
        this(alias, S_REL_USER_GROUP);
    }

    private SRelUserGroup(Name alias, Table<SRelUserGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private SRelUserGroup(Name alias, Table<SRelUserGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DbOriginX.DB_ORIGIN_X;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.S_REL_USER_GROUP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SRelUserGroupRecord> getPrimaryKey() {
        return Keys.KEY_S_REL_USER_GROUP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SRelUserGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<SRelUserGroupRecord>>asList(Keys.KEY_S_REL_USER_GROUP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SRelUserGroup as(String alias) {
        return new SRelUserGroup(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SRelUserGroup as(Name alias) {
        return new SRelUserGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SRelUserGroup rename(String name) {
        return new SRelUserGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SRelUserGroup rename(Name name) {
        return new SRelUserGroup(name, null);
    }
}
