/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISPermission extends Serializable {

    /**
     * Setter for <code>DB_ORIGIN_X.S_PERMISSION.KEY</code>. 「key」- 权限ID
     */
    public ISPermission setKey(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.S_PERMISSION.KEY</code>. 「key」- 权限ID
     */
    public String getKey();

    /**
     * Setter for <code>DB_ORIGIN_X.S_PERMISSION.NAME</code>. 「name」- 权限名称
     */
    public ISPermission setName(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.S_PERMISSION.NAME</code>. 「name」- 权限名称
     */
    public String getName();

    /**
     * Setter for <code>DB_ORIGIN_X.S_PERMISSION.CODE</code>. 「code」- 权限系统码
     */
    public ISPermission setCode(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.S_PERMISSION.CODE</code>. 「code」- 权限系统码
     */
    public String getCode();

    /**
     * Setter for <code>DB_ORIGIN_X.S_PERMISSION.PRIORITY</code>. 「priority」- 权限优先级：角色优先、组优先、用户优先
     */
    public ISPermission setPriority(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.S_PERMISSION.PRIORITY</code>. 「priority」- 权限优先级：角色优先、组优先、用户优先
     */
    public String getPriority();

    /**
     * Setter for <code>DB_ORIGIN_X.S_PERMISSION.MODE</code>. 「mode」- 继承、限制、时域、指定
     */
    public ISPermission setMode(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.S_PERMISSION.MODE</code>. 「mode」- 继承、限制、时域、指定
     */
    public String getMode();

    /**
     * Setter for <code>DB_ORIGIN_X.S_PERMISSION.APP_KEY</code>. 「appKey」- 所属APP的APPKEY
     */
    public ISPermission setAppKey(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.S_PERMISSION.APP_KEY</code>. 「appKey」- 所属APP的APPKEY
     */
    public String getAppKey();

    /**
     * Setter for <code>DB_ORIGIN_X.S_PERMISSION.LANGUAGE</code>. 「language」- 使用的语言
     */
    public ISPermission setLanguage(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.S_PERMISSION.LANGUAGE</code>. 「language」- 使用的语言
     */
    public String getLanguage();

    /**
     * Setter for <code>DB_ORIGIN_X.S_PERMISSION.ACTIVE</code>. 「active」- 是否启用
     */
    public ISPermission setActive(Boolean value);

    /**
     * Getter for <code>DB_ORIGIN_X.S_PERMISSION.ACTIVE</code>. 「active」- 是否启用
     */
    public Boolean getActive();

    /**
     * Setter for <code>DB_ORIGIN_X.S_PERMISSION.METADATA</code>. 「metadata」- 附加配置数据
     */
    public ISPermission setMetadata(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.S_PERMISSION.METADATA</code>. 「metadata」- 附加配置数据
     */
    public String getMetadata();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISPermission
     */
    public void from(cn.vertxup.ix.domain.tables.interfaces.ISPermission from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISPermission
     */
    public <E extends cn.vertxup.ix.domain.tables.interfaces.ISPermission> E into(E into);

    default ISPermission fromJson(io.vertx.core.json.JsonObject json) {
        setKey(json.getString("KEY"));
        setName(json.getString("NAME"));
        setCode(json.getString("CODE"));
        setPriority(json.getString("PRIORITY"));
        setMode(json.getString("MODE"));
        setAppKey(json.getString("APP_KEY"));
        setLanguage(json.getString("LANGUAGE"));
        setActive(json.getBoolean("ACTIVE"));
        setMetadata(json.getString("METADATA"));
        return this;
    }


    default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("KEY",getKey());
        json.put("NAME",getName());
        json.put("CODE",getCode());
        json.put("PRIORITY",getPriority());
        json.put("MODE",getMode());
        json.put("APP_KEY",getAppKey());
        json.put("LANGUAGE",getLanguage());
        json.put("ACTIVE",getActive());
        json.put("METADATA",getMetadata());
        return json;
    }

}
