/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISRelUserGroup extends Serializable {

    /**
     * Setter for <code>DB_ORIGIN_X.S_REL_USER_GROUP.GROUP_ID</code>. 「groupId」- 关联组ID
     */
    public ISRelUserGroup setGroupId(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.S_REL_USER_GROUP.GROUP_ID</code>. 「groupId」- 关联组ID
     */
    public String getGroupId();

    /**
     * Setter for <code>DB_ORIGIN_X.S_REL_USER_GROUP.ROLE_ID</code>. 「roleId」- 关联角色ID
     */
    public ISRelUserGroup setRoleId(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.S_REL_USER_GROUP.ROLE_ID</code>. 「roleId」- 关联角色ID
     */
    public String getRoleId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISRelUserGroup
     */
    public void from(cn.vertxup.ix.domain.tables.interfaces.ISRelUserGroup from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISRelUserGroup
     */
    public <E extends cn.vertxup.ix.domain.tables.interfaces.ISRelUserGroup> E into(E into);

    default ISRelUserGroup fromJson(io.vertx.core.json.JsonObject json) {
        setGroupId(json.getString("GROUP_ID"));
        setRoleId(json.getString("ROLE_ID"));
        return this;
    }


    default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("GROUP_ID",getGroupId());
        json.put("ROLE_ID",getRoleId());
        return json;
    }

}
