/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISRelRolePerm extends Serializable {

    /**
     * Setter for <code>DB_ORIGIN_X.S_REL_ROLE_PERM.PERM_ID</code>. 「permId」- 关联权限ID
     */
    public ISRelRolePerm setPermId(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.S_REL_ROLE_PERM.PERM_ID</code>. 「permId」- 关联权限ID
     */
    public String getPermId();

    /**
     * Setter for <code>DB_ORIGIN_X.S_REL_ROLE_PERM.ROLE_ID</code>. 「roleId」- 关联角色ID
     */
    public ISRelRolePerm setRoleId(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.S_REL_ROLE_PERM.ROLE_ID</code>. 「roleId」- 关联角色ID
     */
    public String getRoleId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISRelRolePerm
     */
    public void from(cn.vertxup.ix.domain.tables.interfaces.ISRelRolePerm from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISRelRolePerm
     */
    public <E extends cn.vertxup.ix.domain.tables.interfaces.ISRelRolePerm> E into(E into);

    default ISRelRolePerm fromJson(io.vertx.core.json.JsonObject json) {
        setPermId(json.getString("PERM_ID"));
        setRoleId(json.getString("ROLE_ID"));
        return this;
    }


    default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("PERM_ID",getPermId());
        json.put("ROLE_ID",getRoleId());
        return json;
    }

}
