/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain.tables.records;


import cn.vertxup.ix.domain.tables.XModule;
import cn.vertxup.ix.domain.tables.interfaces.IXModule;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class XModuleRecord extends UpdatableRecordImpl<XModuleRecord> implements Record10<String, String, String, String, String, String, String, Boolean, String, String>, IXModule {

    private static final long serialVersionUID = 1173556321;

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.KEY</code>. 「key」- 模块唯一主键
     */
    @Override
    public XModuleRecord setKey(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.KEY</code>. 「key」- 模块唯一主键
     */
    @Override
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.NAME</code>. 「name」- 模块名称
     */
    @Override
    public XModuleRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.NAME</code>. 「name」- 模块名称
     */
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.CODE</code>. 「code」- 应用程序编码
     */
    @Override
    public XModuleRecord setCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.CODE</code>. 「code」- 应用程序编码
     */
    @Override
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.CAT</code>. 「cat」- 模块类型
     */
    @Override
    public XModuleRecord setCat(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.CAT</code>. 「cat」- 模块类型
     */
    @Override
    public String getCat() {
        return (String) get(3);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.URL_ENTRY</code>. 「urlEntry」— 模块入口地址
     */
    @Override
    public XModuleRecord setUrlEntry(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.URL_ENTRY</code>. 「urlEntry」— 模块入口地址
     */
    @Override
    public String getUrlEntry() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.APP_ID</code>. 「appId」- 关联的应用程序ID
     */
    @Override
    public XModuleRecord setAppId(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.APP_ID</code>. 「appId」- 关联的应用程序ID
     */
    @Override
    public String getAppId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.MODEL_ID</code>. 「modelId」- 当前模块关联的主模型ID
     */
    @Override
    public XModuleRecord setModelId(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.MODEL_ID</code>. 「modelId」- 当前模块关联的主模型ID
     */
    @Override
    public String getModelId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public XModuleRecord setActive(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.ACTIVE</code>. 「active」- 是否启用
     */
    @Override
    public Boolean getActive() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public XModuleRecord setMetadata(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.METADATA</code>. 「metadata」- 附加配置数据
     */
    @Override
    public String getMetadata() {
        return (String) get(8);
    }

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public XModuleRecord setLanguage(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.LANGUAGE</code>. 「language」- 使用的语言
     */
    @Override
    public String getLanguage() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, String, String, String, Boolean, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, String, String, String, Boolean, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return XModule.X_MODULE.KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return XModule.X_MODULE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return XModule.X_MODULE.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return XModule.X_MODULE.CAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return XModule.X_MODULE.URL_ENTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return XModule.X_MODULE.APP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return XModule.X_MODULE.MODEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return XModule.X_MODULE.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return XModule.X_MODULE.METADATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return XModule.X_MODULE.LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUrlEntry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getMetadata();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUrlEntry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getMetadata();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XModuleRecord value1(String value) {
        setKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XModuleRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XModuleRecord value3(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XModuleRecord value4(String value) {
        setCat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XModuleRecord value5(String value) {
        setUrlEntry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XModuleRecord value6(String value) {
        setAppId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XModuleRecord value7(String value) {
        setModelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XModuleRecord value8(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XModuleRecord value9(String value) {
        setMetadata(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XModuleRecord value10(String value) {
        setLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XModuleRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, Boolean value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IXModule from) {
        setKey(from.getKey());
        setName(from.getName());
        setCode(from.getCode());
        setCat(from.getCat());
        setUrlEntry(from.getUrlEntry());
        setAppId(from.getAppId());
        setModelId(from.getModelId());
        setActive(from.getActive());
        setMetadata(from.getMetadata());
        setLanguage(from.getLanguage());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IXModule> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached XModuleRecord
     */
    public XModuleRecord() {
        super(XModule.X_MODULE);
    }

    /**
     * Create a detached, initialised XModuleRecord
     */
    public XModuleRecord(String key, String name, String code, String cat, String urlEntry, String appId, String modelId, Boolean active, String metadata, String language) {
        super(XModule.X_MODULE);

        set(0, key);
        set(1, name);
        set(2, code);
        set(3, cat);
        set(4, urlEntry);
        set(5, appId);
        set(6, modelId);
        set(7, active);
        set(8, metadata);
        set(9, language);
    }
}
