/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain;


import cn.vertxup.ix.domain.tables.OUser;
import cn.vertxup.ix.domain.tables.SAction;
import cn.vertxup.ix.domain.tables.SGroup;
import cn.vertxup.ix.domain.tables.SPermission;
import cn.vertxup.ix.domain.tables.SRelGroupRole;
import cn.vertxup.ix.domain.tables.SRelPermAction;
import cn.vertxup.ix.domain.tables.SRelResourceMatrix;
import cn.vertxup.ix.domain.tables.SRelRolePerm;
import cn.vertxup.ix.domain.tables.SRelUserGroup;
import cn.vertxup.ix.domain.tables.SRelUserRole;
import cn.vertxup.ix.domain.tables.SResource;
import cn.vertxup.ix.domain.tables.SRole;
import cn.vertxup.ix.domain.tables.SUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in DB_ORIGIN_X
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DB_ORIGIN_X.O_USER</code>.
     */
    public static final OUser O_USER = cn.vertxup.ix.domain.tables.OUser.O_USER;

    /**
     * The table <code>DB_ORIGIN_X.S_ACTION</code>.
     */
    public static final SAction S_ACTION = cn.vertxup.ix.domain.tables.SAction.S_ACTION;

    /**
     * The table <code>DB_ORIGIN_X.S_GROUP</code>.
     */
    public static final SGroup S_GROUP = cn.vertxup.ix.domain.tables.SGroup.S_GROUP;

    /**
     * The table <code>DB_ORIGIN_X.S_PERMISSION</code>.
     */
    public static final SPermission S_PERMISSION = cn.vertxup.ix.domain.tables.SPermission.S_PERMISSION;

    /**
     * The table <code>DB_ORIGIN_X.S_REL_GROUP_ROLE</code>.
     */
    public static final SRelGroupRole S_REL_GROUP_ROLE = cn.vertxup.ix.domain.tables.SRelGroupRole.S_REL_GROUP_ROLE;

    /**
     * The table <code>DB_ORIGIN_X.S_REL_PERM_ACTION</code>.
     */
    public static final SRelPermAction S_REL_PERM_ACTION = cn.vertxup.ix.domain.tables.SRelPermAction.S_REL_PERM_ACTION;

    /**
     * The table <code>DB_ORIGIN_X.S_REL_RESOURCE_MATRIX</code>.
     */
    public static final SRelResourceMatrix S_REL_RESOURCE_MATRIX = cn.vertxup.ix.domain.tables.SRelResourceMatrix.S_REL_RESOURCE_MATRIX;

    /**
     * The table <code>DB_ORIGIN_X.S_REL_ROLE_PERM</code>.
     */
    public static final SRelRolePerm S_REL_ROLE_PERM = cn.vertxup.ix.domain.tables.SRelRolePerm.S_REL_ROLE_PERM;

    /**
     * The table <code>DB_ORIGIN_X.S_REL_USER_GROUP</code>.
     */
    public static final SRelUserGroup S_REL_USER_GROUP = cn.vertxup.ix.domain.tables.SRelUserGroup.S_REL_USER_GROUP;

    /**
     * The table <code>DB_ORIGIN_X.S_REL_USER_ROLE</code>.
     */
    public static final SRelUserRole S_REL_USER_ROLE = cn.vertxup.ix.domain.tables.SRelUserRole.S_REL_USER_ROLE;

    /**
     * The table <code>DB_ORIGIN_X.S_RESOURCE</code>.
     */
    public static final SResource S_RESOURCE = cn.vertxup.ix.domain.tables.SResource.S_RESOURCE;

    /**
     * The table <code>DB_ORIGIN_X.S_ROLE</code>.
     */
    public static final SRole S_ROLE = cn.vertxup.ix.domain.tables.SRole.S_ROLE;

    /**
     * The table <code>DB_ORIGIN_X.S_USER</code>.
     */
    public static final SUser S_USER = cn.vertxup.ix.domain.tables.SUser.S_USER;
}
