/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain.tables.pojos;


import cn.vertxup.ix.domain.tables.interfaces.IXApp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class XApp implements IXApp {

    private static final long serialVersionUID = -867131419;

    private String  key;
    private String  name;
    private String  code;
    private String  title;
    private String  logo;
    private String  domain;
    private String  path;
    private String  route;
    private String  appKey;
    private Integer appPort;
    private String  urlEntry;
    private String  urlMain;
    private Boolean active;
    private String  language;
    private String  metadata;

    public XApp() {}

    public XApp(XApp value) {
        this.key = value.key;
        this.name = value.name;
        this.code = value.code;
        this.title = value.title;
        this.logo = value.logo;
        this.domain = value.domain;
        this.path = value.path;
        this.route = value.route;
        this.appKey = value.appKey;
        this.appPort = value.appPort;
        this.urlEntry = value.urlEntry;
        this.urlMain = value.urlMain;
        this.active = value.active;
        this.language = value.language;
        this.metadata = value.metadata;
    }

    public XApp(
        String  key,
        String  name,
        String  code,
        String  title,
        String  logo,
        String  domain,
        String  path,
        String  route,
        String  appKey,
        Integer appPort,
        String  urlEntry,
        String  urlMain,
        Boolean active,
        String  language,
        String  metadata
    ) {
        this.key = key;
        this.name = name;
        this.code = code;
        this.title = title;
        this.logo = logo;
        this.domain = domain;
        this.path = path;
        this.route = route;
        this.appKey = appKey;
        this.appPort = appPort;
        this.urlEntry = urlEntry;
        this.urlMain = urlMain;
        this.active = active;
        this.language = language;
        this.metadata = metadata;
    }

    @Override
    public String getKey() {
        return this.key;
    }

    @Override
    public XApp setKey(String key) {
        this.key = key;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public XApp setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getCode() {
        return this.code;
    }

    @Override
    public XApp setCode(String code) {
        this.code = code;
        return this;
    }

    @Override
    public String getTitle() {
        return this.title;
    }

    @Override
    public XApp setTitle(String title) {
        this.title = title;
        return this;
    }

    @Override
    public String getLogo() {
        return this.logo;
    }

    @Override
    public XApp setLogo(String logo) {
        this.logo = logo;
        return this;
    }

    @Override
    public String getDomain() {
        return this.domain;
    }

    @Override
    public XApp setDomain(String domain) {
        this.domain = domain;
        return this;
    }

    @Override
    public String getPath() {
        return this.path;
    }

    @Override
    public XApp setPath(String path) {
        this.path = path;
        return this;
    }

    @Override
    public String getRoute() {
        return this.route;
    }

    @Override
    public XApp setRoute(String route) {
        this.route = route;
        return this;
    }

    @Override
    public String getAppKey() {
        return this.appKey;
    }

    @Override
    public XApp setAppKey(String appKey) {
        this.appKey = appKey;
        return this;
    }

    @Override
    public Integer getAppPort() {
        return this.appPort;
    }

    @Override
    public XApp setAppPort(Integer appPort) {
        this.appPort = appPort;
        return this;
    }

    @Override
    public String getUrlEntry() {
        return this.urlEntry;
    }

    @Override
    public XApp setUrlEntry(String urlEntry) {
        this.urlEntry = urlEntry;
        return this;
    }

    @Override
    public String getUrlMain() {
        return this.urlMain;
    }

    @Override
    public XApp setUrlMain(String urlMain) {
        this.urlMain = urlMain;
        return this;
    }

    @Override
    public Boolean getActive() {
        return this.active;
    }

    @Override
    public XApp setActive(Boolean active) {
        this.active = active;
        return this;
    }

    @Override
    public String getLanguage() {
        return this.language;
    }

    @Override
    public XApp setLanguage(String language) {
        this.language = language;
        return this;
    }

    @Override
    public String getMetadata() {
        return this.metadata;
    }

    @Override
    public XApp setMetadata(String metadata) {
        this.metadata = metadata;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("XApp (");

        sb.append(key);
        sb.append(", ").append(name);
        sb.append(", ").append(code);
        sb.append(", ").append(title);
        sb.append(", ").append(logo);
        sb.append(", ").append(domain);
        sb.append(", ").append(path);
        sb.append(", ").append(route);
        sb.append(", ").append(appKey);
        sb.append(", ").append(appPort);
        sb.append(", ").append(urlEntry);
        sb.append(", ").append(urlMain);
        sb.append(", ").append(active);
        sb.append(", ").append(language);
        sb.append(", ").append(metadata);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IXApp from) {
        setKey(from.getKey());
        setName(from.getName());
        setCode(from.getCode());
        setTitle(from.getTitle());
        setLogo(from.getLogo());
        setDomain(from.getDomain());
        setPath(from.getPath());
        setRoute(from.getRoute());
        setAppKey(from.getAppKey());
        setAppPort(from.getAppPort());
        setUrlEntry(from.getUrlEntry());
        setUrlMain(from.getUrlMain());
        setActive(from.getActive());
        setLanguage(from.getLanguage());
        setMetadata(from.getMetadata());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IXApp> E into(E into) {
        into.from(this);
        return into;
    }

    public XApp(io.vertx.core.json.JsonObject json) {
        fromJson(json);
    }
}
