/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain.tables.pojos;


import cn.vertxup.ix.domain.tables.interfaces.IXModule;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class XModule implements IXModule {

    private static final long serialVersionUID = 1657843222;

    private String  key;
    private String  name;
    private String  code;
    private String  cat;
    private String  urlEntry;
    private String  appId;
    private String  modelId;
    private Boolean active;
    private String  metadata;
    private String  language;

    public XModule() {}

    public XModule(XModule value) {
        this.key = value.key;
        this.name = value.name;
        this.code = value.code;
        this.cat = value.cat;
        this.urlEntry = value.urlEntry;
        this.appId = value.appId;
        this.modelId = value.modelId;
        this.active = value.active;
        this.metadata = value.metadata;
        this.language = value.language;
    }

    public XModule(
        String  key,
        String  name,
        String  code,
        String  cat,
        String  urlEntry,
        String  appId,
        String  modelId,
        Boolean active,
        String  metadata,
        String  language
    ) {
        this.key = key;
        this.name = name;
        this.code = code;
        this.cat = cat;
        this.urlEntry = urlEntry;
        this.appId = appId;
        this.modelId = modelId;
        this.active = active;
        this.metadata = metadata;
        this.language = language;
    }

    @Override
    public String getKey() {
        return this.key;
    }

    @Override
    public XModule setKey(String key) {
        this.key = key;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public XModule setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getCode() {
        return this.code;
    }

    @Override
    public XModule setCode(String code) {
        this.code = code;
        return this;
    }

    @Override
    public String getCat() {
        return this.cat;
    }

    @Override
    public XModule setCat(String cat) {
        this.cat = cat;
        return this;
    }

    @Override
    public String getUrlEntry() {
        return this.urlEntry;
    }

    @Override
    public XModule setUrlEntry(String urlEntry) {
        this.urlEntry = urlEntry;
        return this;
    }

    @Override
    public String getAppId() {
        return this.appId;
    }

    @Override
    public XModule setAppId(String appId) {
        this.appId = appId;
        return this;
    }

    @Override
    public String getModelId() {
        return this.modelId;
    }

    @Override
    public XModule setModelId(String modelId) {
        this.modelId = modelId;
        return this;
    }

    @Override
    public Boolean getActive() {
        return this.active;
    }

    @Override
    public XModule setActive(Boolean active) {
        this.active = active;
        return this;
    }

    @Override
    public String getMetadata() {
        return this.metadata;
    }

    @Override
    public XModule setMetadata(String metadata) {
        this.metadata = metadata;
        return this;
    }

    @Override
    public String getLanguage() {
        return this.language;
    }

    @Override
    public XModule setLanguage(String language) {
        this.language = language;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("XModule (");

        sb.append(key);
        sb.append(", ").append(name);
        sb.append(", ").append(code);
        sb.append(", ").append(cat);
        sb.append(", ").append(urlEntry);
        sb.append(", ").append(appId);
        sb.append(", ").append(modelId);
        sb.append(", ").append(active);
        sb.append(", ").append(metadata);
        sb.append(", ").append(language);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IXModule from) {
        setKey(from.getKey());
        setName(from.getName());
        setCode(from.getCode());
        setCat(from.getCat());
        setUrlEntry(from.getUrlEntry());
        setAppId(from.getAppId());
        setModelId(from.getModelId());
        setActive(from.getActive());
        setMetadata(from.getMetadata());
        setLanguage(from.getLanguage());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IXModule> E into(E into) {
        into.from(this);
        return into;
    }

    public XModule(io.vertx.core.json.JsonObject json) {
        fromJson(json);
    }
}
