/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain;


import cn.vertxup.ix.domain.tables.XApp;
import cn.vertxup.ix.domain.tables.XAttachment;
import cn.vertxup.ix.domain.tables.XCategory;
import cn.vertxup.ix.domain.tables.XMenu;
import cn.vertxup.ix.domain.tables.XModule;
import cn.vertxup.ix.domain.tables.XSource;
import cn.vertxup.ix.domain.tables.XTabular;
import cn.vertxup.ix.domain.tables.records.XAppRecord;
import cn.vertxup.ix.domain.tables.records.XAttachmentRecord;
import cn.vertxup.ix.domain.tables.records.XCategoryRecord;
import cn.vertxup.ix.domain.tables.records.XMenuRecord;
import cn.vertxup.ix.domain.tables.records.XModuleRecord;
import cn.vertxup.ix.domain.tables.records.XSourceRecord;
import cn.vertxup.ix.domain.tables.records.XTabularRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>DB_ORIGIN_X</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<XAppRecord> KEY_X_APP_PRIMARY = UniqueKeys0.KEY_X_APP_PRIMARY;
    public static final UniqueKey<XAppRecord> KEY_X_APP_NAME = UniqueKeys0.KEY_X_APP_NAME;
    public static final UniqueKey<XAppRecord> KEY_X_APP_CODE = UniqueKeys0.KEY_X_APP_CODE;
    public static final UniqueKey<XAppRecord> KEY_X_APP_PATH = UniqueKeys0.KEY_X_APP_PATH;
    public static final UniqueKey<XAppRecord> KEY_X_APP_PATH_2 = UniqueKeys0.KEY_X_APP_PATH_2;
    public static final UniqueKey<XAttachmentRecord> KEY_X_ATTACHMENT_PRIMARY = UniqueKeys0.KEY_X_ATTACHMENT_PRIMARY;
    public static final UniqueKey<XAttachmentRecord> KEY_X_ATTACHMENT_FILE_KEY = UniqueKeys0.KEY_X_ATTACHMENT_FILE_KEY;
    public static final UniqueKey<XAttachmentRecord> KEY_X_ATTACHMENT_FILE_URL = UniqueKeys0.KEY_X_ATTACHMENT_FILE_URL;
    public static final UniqueKey<XAttachmentRecord> KEY_X_ATTACHMENT_FILE_PATH = UniqueKeys0.KEY_X_ATTACHMENT_FILE_PATH;
    public static final UniqueKey<XCategoryRecord> KEY_X_CATEGORY_PRIMARY = UniqueKeys0.KEY_X_CATEGORY_PRIMARY;
    public static final UniqueKey<XCategoryRecord> KEY_X_CATEGORY_APP_ID = UniqueKeys0.KEY_X_CATEGORY_APP_ID;
    public static final UniqueKey<XMenuRecord> KEY_X_MENU_PRIMARY = UniqueKeys0.KEY_X_MENU_PRIMARY;
    public static final UniqueKey<XMenuRecord> KEY_X_MENU_NAME = UniqueKeys0.KEY_X_MENU_NAME;
    public static final UniqueKey<XModuleRecord> KEY_X_MODULE_PRIMARY = UniqueKeys0.KEY_X_MODULE_PRIMARY;
    public static final UniqueKey<XModuleRecord> KEY_X_MODULE_URL_ENTRY = UniqueKeys0.KEY_X_MODULE_URL_ENTRY;
    public static final UniqueKey<XSourceRecord> KEY_X_SOURCE_PRIMARY = UniqueKeys0.KEY_X_SOURCE_PRIMARY;
    public static final UniqueKey<XSourceRecord> KEY_X_SOURCE_APP_ID = UniqueKeys0.KEY_X_SOURCE_APP_ID;
    public static final UniqueKey<XTabularRecord> KEY_X_TABULAR_PRIMARY = UniqueKeys0.KEY_X_TABULAR_PRIMARY;
    public static final UniqueKey<XTabularRecord> KEY_X_TABULAR_APP_ID = UniqueKeys0.KEY_X_TABULAR_APP_ID;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<XAppRecord> KEY_X_APP_PRIMARY = Internal.createUniqueKey(XApp.X_APP, "KEY_X_APP_PRIMARY", XApp.X_APP.KEY);
        public static final UniqueKey<XAppRecord> KEY_X_APP_NAME = Internal.createUniqueKey(XApp.X_APP, "KEY_X_APP_NAME", XApp.X_APP.NAME);
        public static final UniqueKey<XAppRecord> KEY_X_APP_CODE = Internal.createUniqueKey(XApp.X_APP, "KEY_X_APP_CODE", XApp.X_APP.CODE);
        public static final UniqueKey<XAppRecord> KEY_X_APP_PATH = Internal.createUniqueKey(XApp.X_APP, "KEY_X_APP_PATH", XApp.X_APP.PATH, XApp.X_APP.URL_ENTRY);
        public static final UniqueKey<XAppRecord> KEY_X_APP_PATH_2 = Internal.createUniqueKey(XApp.X_APP, "KEY_X_APP_PATH_2", XApp.X_APP.PATH, XApp.X_APP.URL_MAIN);
        public static final UniqueKey<XAttachmentRecord> KEY_X_ATTACHMENT_PRIMARY = Internal.createUniqueKey(XAttachment.X_ATTACHMENT, "KEY_X_ATTACHMENT_PRIMARY", XAttachment.X_ATTACHMENT.KEY);
        public static final UniqueKey<XAttachmentRecord> KEY_X_ATTACHMENT_FILE_KEY = Internal.createUniqueKey(XAttachment.X_ATTACHMENT, "KEY_X_ATTACHMENT_FILE_KEY", XAttachment.X_ATTACHMENT.FILE_KEY);
        public static final UniqueKey<XAttachmentRecord> KEY_X_ATTACHMENT_FILE_URL = Internal.createUniqueKey(XAttachment.X_ATTACHMENT, "KEY_X_ATTACHMENT_FILE_URL", XAttachment.X_ATTACHMENT.FILE_URL);
        public static final UniqueKey<XAttachmentRecord> KEY_X_ATTACHMENT_FILE_PATH = Internal.createUniqueKey(XAttachment.X_ATTACHMENT, "KEY_X_ATTACHMENT_FILE_PATH", XAttachment.X_ATTACHMENT.FILE_PATH);
        public static final UniqueKey<XCategoryRecord> KEY_X_CATEGORY_PRIMARY = Internal.createUniqueKey(XCategory.X_CATEGORY, "KEY_X_CATEGORY_PRIMARY", XCategory.X_CATEGORY.KEY);
        public static final UniqueKey<XCategoryRecord> KEY_X_CATEGORY_APP_ID = Internal.createUniqueKey(XCategory.X_CATEGORY, "KEY_X_CATEGORY_APP_ID", XCategory.X_CATEGORY.APP_ID, XCategory.X_CATEGORY.TYPE, XCategory.X_CATEGORY.CODE);
        public static final UniqueKey<XMenuRecord> KEY_X_MENU_PRIMARY = Internal.createUniqueKey(XMenu.X_MENU, "KEY_X_MENU_PRIMARY", XMenu.X_MENU.KEY);
        public static final UniqueKey<XMenuRecord> KEY_X_MENU_NAME = Internal.createUniqueKey(XMenu.X_MENU, "KEY_X_MENU_NAME", XMenu.X_MENU.NAME, XMenu.X_MENU.APP_ID);
        public static final UniqueKey<XModuleRecord> KEY_X_MODULE_PRIMARY = Internal.createUniqueKey(XModule.X_MODULE, "KEY_X_MODULE_PRIMARY", XModule.X_MODULE.KEY);
        public static final UniqueKey<XModuleRecord> KEY_X_MODULE_URL_ENTRY = Internal.createUniqueKey(XModule.X_MODULE, "KEY_X_MODULE_URL_ENTRY", XModule.X_MODULE.URL_ENTRY);
        public static final UniqueKey<XSourceRecord> KEY_X_SOURCE_PRIMARY = Internal.createUniqueKey(XSource.X_SOURCE, "KEY_X_SOURCE_PRIMARY", XSource.X_SOURCE.KEY);
        public static final UniqueKey<XSourceRecord> KEY_X_SOURCE_APP_ID = Internal.createUniqueKey(XSource.X_SOURCE, "KEY_X_SOURCE_APP_ID", XSource.X_SOURCE.APP_ID);
        public static final UniqueKey<XTabularRecord> KEY_X_TABULAR_PRIMARY = Internal.createUniqueKey(XTabular.X_TABULAR, "KEY_X_TABULAR_PRIMARY", XTabular.X_TABULAR.KEY);
        public static final UniqueKey<XTabularRecord> KEY_X_TABULAR_APP_ID = Internal.createUniqueKey(XTabular.X_TABULAR, "KEY_X_TABULAR_APP_ID", XTabular.X_TABULAR.APP_ID, XTabular.X_TABULAR.TYPE, XTabular.X_TABULAR.CODE);
    }
}
