/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain;


import cn.vertxup.ix.domain.tables.XApp;
import cn.vertxup.ix.domain.tables.XAttachment;
import cn.vertxup.ix.domain.tables.XCategory;
import cn.vertxup.ix.domain.tables.XMenu;
import cn.vertxup.ix.domain.tables.XModule;
import cn.vertxup.ix.domain.tables.XSource;
import cn.vertxup.ix.domain.tables.XTabular;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in DB_ORIGIN_X
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DB_ORIGIN_X.X_APP</code>.
     */
    public static final XApp X_APP = cn.vertxup.ix.domain.tables.XApp.X_APP;

    /**
     * The table <code>DB_ORIGIN_X.X_ATTACHMENT</code>.
     */
    public static final XAttachment X_ATTACHMENT = cn.vertxup.ix.domain.tables.XAttachment.X_ATTACHMENT;

    /**
     * The table <code>DB_ORIGIN_X.X_CATEGORY</code>.
     */
    public static final XCategory X_CATEGORY = cn.vertxup.ix.domain.tables.XCategory.X_CATEGORY;

    /**
     * The table <code>DB_ORIGIN_X.X_MENU</code>.
     */
    public static final XMenu X_MENU = cn.vertxup.ix.domain.tables.XMenu.X_MENU;

    /**
     * The table <code>DB_ORIGIN_X.X_MODULE</code>.
     */
    public static final XModule X_MODULE = cn.vertxup.ix.domain.tables.XModule.X_MODULE;

    /**
     * The table <code>DB_ORIGIN_X.X_SOURCE</code>.
     */
    public static final XSource X_SOURCE = cn.vertxup.ix.domain.tables.XSource.X_SOURCE;

    /**
     * The table <code>DB_ORIGIN_X.X_TABULAR</code>.
     */
    public static final XTabular X_TABULAR = cn.vertxup.ix.domain.tables.XTabular.X_TABULAR;
}
