/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain.tables.pojos;


import cn.vertxup.ix.domain.tables.interfaces.ISAction;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SAction implements ISAction {

    private static final long serialVersionUID = -1652032560;

    private String  key;
    private String  name;
    private String  code;
    private Integer level;
    private String  priority;
    private String  category;
    private String  appKey;
    private String  language;
    private Boolean active;
    private String  metadata;
    private String  resourceId;

    public SAction() {}

    public SAction(SAction value) {
        this.key = value.key;
        this.name = value.name;
        this.code = value.code;
        this.level = value.level;
        this.priority = value.priority;
        this.category = value.category;
        this.appKey = value.appKey;
        this.language = value.language;
        this.active = value.active;
        this.metadata = value.metadata;
        this.resourceId = value.resourceId;
    }

    public SAction(
        String  key,
        String  name,
        String  code,
        Integer level,
        String  priority,
        String  category,
        String  appKey,
        String  language,
        Boolean active,
        String  metadata,
        String  resourceId
    ) {
        this.key = key;
        this.name = name;
        this.code = code;
        this.level = level;
        this.priority = priority;
        this.category = category;
        this.appKey = appKey;
        this.language = language;
        this.active = active;
        this.metadata = metadata;
        this.resourceId = resourceId;
    }

    @Override
    public String getKey() {
        return this.key;
    }

    @Override
    public SAction setKey(String key) {
        this.key = key;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public SAction setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getCode() {
        return this.code;
    }

    @Override
    public SAction setCode(String code) {
        this.code = code;
        return this;
    }

    @Override
    public Integer getLevel() {
        return this.level;
    }

    @Override
    public SAction setLevel(Integer level) {
        this.level = level;
        return this;
    }

    @Override
    public String getPriority() {
        return this.priority;
    }

    @Override
    public SAction setPriority(String priority) {
        this.priority = priority;
        return this;
    }

    @Override
    public String getCategory() {
        return this.category;
    }

    @Override
    public SAction setCategory(String category) {
        this.category = category;
        return this;
    }

    @Override
    public String getAppKey() {
        return this.appKey;
    }

    @Override
    public SAction setAppKey(String appKey) {
        this.appKey = appKey;
        return this;
    }

    @Override
    public String getLanguage() {
        return this.language;
    }

    @Override
    public SAction setLanguage(String language) {
        this.language = language;
        return this;
    }

    @Override
    public Boolean getActive() {
        return this.active;
    }

    @Override
    public SAction setActive(Boolean active) {
        this.active = active;
        return this;
    }

    @Override
    public String getMetadata() {
        return this.metadata;
    }

    @Override
    public SAction setMetadata(String metadata) {
        this.metadata = metadata;
        return this;
    }

    @Override
    public String getResourceId() {
        return this.resourceId;
    }

    @Override
    public SAction setResourceId(String resourceId) {
        this.resourceId = resourceId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SAction (");

        sb.append(key);
        sb.append(", ").append(name);
        sb.append(", ").append(code);
        sb.append(", ").append(level);
        sb.append(", ").append(priority);
        sb.append(", ").append(category);
        sb.append(", ").append(appKey);
        sb.append(", ").append(language);
        sb.append(", ").append(active);
        sb.append(", ").append(metadata);
        sb.append(", ").append(resourceId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ISAction from) {
        setKey(from.getKey());
        setName(from.getName());
        setCode(from.getCode());
        setLevel(from.getLevel());
        setPriority(from.getPriority());
        setCategory(from.getCategory());
        setAppKey(from.getAppKey());
        setLanguage(from.getLanguage());
        setActive(from.getActive());
        setMetadata(from.getMetadata());
        setResourceId(from.getResourceId());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ISAction> E into(E into) {
        into.from(this);
        return into;
    }

    public SAction(io.vertx.core.json.JsonObject json) {
        fromJson(json);
    }
}
