/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain.tables.pojos;


import cn.vertxup.ix.domain.tables.interfaces.ISPermission;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SPermission implements ISPermission {

    private static final long serialVersionUID = -1022243626;

    private String  key;
    private String  name;
    private String  code;
    private String  priority;
    private String  mode;
    private String  appKey;
    private String  language;
    private Boolean active;
    private String  metadata;

    public SPermission() {}

    public SPermission(SPermission value) {
        this.key = value.key;
        this.name = value.name;
        this.code = value.code;
        this.priority = value.priority;
        this.mode = value.mode;
        this.appKey = value.appKey;
        this.language = value.language;
        this.active = value.active;
        this.metadata = value.metadata;
    }

    public SPermission(
        String  key,
        String  name,
        String  code,
        String  priority,
        String  mode,
        String  appKey,
        String  language,
        Boolean active,
        String  metadata
    ) {
        this.key = key;
        this.name = name;
        this.code = code;
        this.priority = priority;
        this.mode = mode;
        this.appKey = appKey;
        this.language = language;
        this.active = active;
        this.metadata = metadata;
    }

    @Override
    public String getKey() {
        return this.key;
    }

    @Override
    public SPermission setKey(String key) {
        this.key = key;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public SPermission setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String getCode() {
        return this.code;
    }

    @Override
    public SPermission setCode(String code) {
        this.code = code;
        return this;
    }

    @Override
    public String getPriority() {
        return this.priority;
    }

    @Override
    public SPermission setPriority(String priority) {
        this.priority = priority;
        return this;
    }

    @Override
    public String getMode() {
        return this.mode;
    }

    @Override
    public SPermission setMode(String mode) {
        this.mode = mode;
        return this;
    }

    @Override
    public String getAppKey() {
        return this.appKey;
    }

    @Override
    public SPermission setAppKey(String appKey) {
        this.appKey = appKey;
        return this;
    }

    @Override
    public String getLanguage() {
        return this.language;
    }

    @Override
    public SPermission setLanguage(String language) {
        this.language = language;
        return this;
    }

    @Override
    public Boolean getActive() {
        return this.active;
    }

    @Override
    public SPermission setActive(Boolean active) {
        this.active = active;
        return this;
    }

    @Override
    public String getMetadata() {
        return this.metadata;
    }

    @Override
    public SPermission setMetadata(String metadata) {
        this.metadata = metadata;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SPermission (");

        sb.append(key);
        sb.append(", ").append(name);
        sb.append(", ").append(code);
        sb.append(", ").append(priority);
        sb.append(", ").append(mode);
        sb.append(", ").append(appKey);
        sb.append(", ").append(language);
        sb.append(", ").append(active);
        sb.append(", ").append(metadata);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ISPermission from) {
        setKey(from.getKey());
        setName(from.getName());
        setCode(from.getCode());
        setPriority(from.getPriority());
        setMode(from.getMode());
        setAppKey(from.getAppKey());
        setLanguage(from.getLanguage());
        setActive(from.getActive());
        setMetadata(from.getMetadata());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ISPermission> E into(E into) {
        into.from(this);
        return into;
    }

    public SPermission(io.vertx.core.json.JsonObject json) {
        fromJson(json);
    }
}
