/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain.tables.pojos;


import cn.vertxup.ix.domain.tables.interfaces.ISUser;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SUser implements ISUser {

    private static final long serialVersionUID = 240010989;

    private String  key;
    private String  username;
    private String  realname;
    private String  alias;
    private String  mobile;
    private String  email;
    private String  password;
    private String  category;
    private String  appKey;
    private String  secret;
    private String  modelId;
    private String  modelKey;
    private String  language;
    private Boolean active;
    private String  metadata;

    public SUser() {}

    public SUser(SUser value) {
        this.key = value.key;
        this.username = value.username;
        this.realname = value.realname;
        this.alias = value.alias;
        this.mobile = value.mobile;
        this.email = value.email;
        this.password = value.password;
        this.category = value.category;
        this.appKey = value.appKey;
        this.secret = value.secret;
        this.modelId = value.modelId;
        this.modelKey = value.modelKey;
        this.language = value.language;
        this.active = value.active;
        this.metadata = value.metadata;
    }

    public SUser(
        String  key,
        String  username,
        String  realname,
        String  alias,
        String  mobile,
        String  email,
        String  password,
        String  category,
        String  appKey,
        String  secret,
        String  modelId,
        String  modelKey,
        String  language,
        Boolean active,
        String  metadata
    ) {
        this.key = key;
        this.username = username;
        this.realname = realname;
        this.alias = alias;
        this.mobile = mobile;
        this.email = email;
        this.password = password;
        this.category = category;
        this.appKey = appKey;
        this.secret = secret;
        this.modelId = modelId;
        this.modelKey = modelKey;
        this.language = language;
        this.active = active;
        this.metadata = metadata;
    }

    @Override
    public String getKey() {
        return this.key;
    }

    @Override
    public SUser setKey(String key) {
        this.key = key;
        return this;
    }

    @Override
    public String getUsername() {
        return this.username;
    }

    @Override
    public SUser setUsername(String username) {
        this.username = username;
        return this;
    }

    @Override
    public String getRealname() {
        return this.realname;
    }

    @Override
    public SUser setRealname(String realname) {
        this.realname = realname;
        return this;
    }

    @Override
    public String getAlias() {
        return this.alias;
    }

    @Override
    public SUser setAlias(String alias) {
        this.alias = alias;
        return this;
    }

    @Override
    public String getMobile() {
        return this.mobile;
    }

    @Override
    public SUser setMobile(String mobile) {
        this.mobile = mobile;
        return this;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public SUser setEmail(String email) {
        this.email = email;
        return this;
    }

    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public SUser setPassword(String password) {
        this.password = password;
        return this;
    }

    @Override
    public String getCategory() {
        return this.category;
    }

    @Override
    public SUser setCategory(String category) {
        this.category = category;
        return this;
    }

    @Override
    public String getAppKey() {
        return this.appKey;
    }

    @Override
    public SUser setAppKey(String appKey) {
        this.appKey = appKey;
        return this;
    }

    @Override
    public String getSecret() {
        return this.secret;
    }

    @Override
    public SUser setSecret(String secret) {
        this.secret = secret;
        return this;
    }

    @Override
    public String getModelId() {
        return this.modelId;
    }

    @Override
    public SUser setModelId(String modelId) {
        this.modelId = modelId;
        return this;
    }

    @Override
    public String getModelKey() {
        return this.modelKey;
    }

    @Override
    public SUser setModelKey(String modelKey) {
        this.modelKey = modelKey;
        return this;
    }

    @Override
    public String getLanguage() {
        return this.language;
    }

    @Override
    public SUser setLanguage(String language) {
        this.language = language;
        return this;
    }

    @Override
    public Boolean getActive() {
        return this.active;
    }

    @Override
    public SUser setActive(Boolean active) {
        this.active = active;
        return this;
    }

    @Override
    public String getMetadata() {
        return this.metadata;
    }

    @Override
    public SUser setMetadata(String metadata) {
        this.metadata = metadata;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SUser (");

        sb.append(key);
        sb.append(", ").append(username);
        sb.append(", ").append(realname);
        sb.append(", ").append(alias);
        sb.append(", ").append(mobile);
        sb.append(", ").append(email);
        sb.append(", ").append(password);
        sb.append(", ").append(category);
        sb.append(", ").append(appKey);
        sb.append(", ").append(secret);
        sb.append(", ").append(modelId);
        sb.append(", ").append(modelKey);
        sb.append(", ").append(language);
        sb.append(", ").append(active);
        sb.append(", ").append(metadata);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ISUser from) {
        setKey(from.getKey());
        setUsername(from.getUsername());
        setRealname(from.getRealname());
        setAlias(from.getAlias());
        setMobile(from.getMobile());
        setEmail(from.getEmail());
        setPassword(from.getPassword());
        setCategory(from.getCategory());
        setAppKey(from.getAppKey());
        setSecret(from.getSecret());
        setModelId(from.getModelId());
        setModelKey(from.getModelKey());
        setLanguage(from.getLanguage());
        setActive(from.getActive());
        setMetadata(from.getMetadata());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ISUser> E into(E into) {
        into.from(this);
        return into;
    }

    public SUser(io.vertx.core.json.JsonObject json) {
        fromJson(json);
    }
}
