/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.ix.domain.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IXModule extends Serializable {

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.KEY</code>. 「key」- 模块唯一主键
     */
    public IXModule setKey(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.KEY</code>. 「key」- 模块唯一主键
     */
    public String getKey();

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.NAME</code>. 「name」- 模块名称
     */
    public IXModule setName(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.NAME</code>. 「name」- 模块名称
     */
    public String getName();

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.CODE</code>. 「code」- 应用程序编码
     */
    public IXModule setCode(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.CODE</code>. 「code」- 应用程序编码
     */
    public String getCode();

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.CAT</code>. 「cat」- 模块类型
     */
    public IXModule setCat(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.CAT</code>. 「cat」- 模块类型
     */
    public String getCat();

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.URL_ENTRY</code>. 「urlEntry」— 模块入口地址
     */
    public IXModule setUrlEntry(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.URL_ENTRY</code>. 「urlEntry」— 模块入口地址
     */
    public String getUrlEntry();

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.APP_ID</code>. 「appId」- 关联的应用程序ID
     */
    public IXModule setAppId(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.APP_ID</code>. 「appId」- 关联的应用程序ID
     */
    public String getAppId();

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.MODEL_ID</code>. 「modelId」- 当前模块关联的主模型ID
     */
    public IXModule setModelId(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.MODEL_ID</code>. 「modelId」- 当前模块关联的主模型ID
     */
    public String getModelId();

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.ACTIVE</code>. 「active」- 是否启用
     */
    public IXModule setActive(Boolean value);

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.ACTIVE</code>. 「active」- 是否启用
     */
    public Boolean getActive();

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.METADATA</code>. 「metadata」- 附加配置数据
     */
    public IXModule setMetadata(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.METADATA</code>. 「metadata」- 附加配置数据
     */
    public String getMetadata();

    /**
     * Setter for <code>DB_ORIGIN_X.X_MODULE.LANGUAGE</code>. 「language」- 使用的语言
     */
    public IXModule setLanguage(String value);

    /**
     * Getter for <code>DB_ORIGIN_X.X_MODULE.LANGUAGE</code>. 「language」- 使用的语言
     */
    public String getLanguage();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IXModule
     */
    public void from(cn.vertxup.ix.domain.tables.interfaces.IXModule from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IXModule
     */
    public <E extends cn.vertxup.ix.domain.tables.interfaces.IXModule> E into(E into);

    default IXModule fromJson(io.vertx.core.json.JsonObject json) {
        setKey(json.getString("KEY"));
        setName(json.getString("NAME"));
        setCode(json.getString("CODE"));
        setCat(json.getString("CAT"));
        setUrlEntry(json.getString("URL_ENTRY"));
        setAppId(json.getString("APP_ID"));
        setModelId(json.getString("MODEL_ID"));
        setActive(json.getBoolean("ACTIVE"));
        setMetadata(json.getString("METADATA"));
        setLanguage(json.getString("LANGUAGE"));
        return this;
    }


    default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("KEY",getKey());
        json.put("NAME",getName());
        json.put("CODE",getCode());
        json.put("CAT",getCat());
        json.put("URL_ENTRY",getUrlEntry());
        json.put("APP_ID",getAppId());
        json.put("MODEL_ID",getModelId());
        json.put("ACTIVE",getActive());
        json.put("METADATA",getMetadata());
        json.put("LANGUAGE",getLanguage());
        return json;
    }

}
